#!/bin/bash
# If the log file is empty (82 bytes), remove it and kill the running poller

# Config section - set the absolute path to where ginserv.py lives
scriptdir=/usr/local/src/ginlong2pvoutput
# End of config


lastlog=$(ls -tr ginserv.log*|tail -1)

if [ "$lastlog" = "ginserv.log" ]; then
  # ginserv.log is the last one
  logsize=$(stat -c "%s" "$lastlog")
  if [ $logsize -le 82 ]; then
    # File is still just the header - tidy up
    rm -f "$lastlog"
    ./killginservpoller
  fi
fi
