#!/bin/bash
# Stop the current ginserv poller, so that runginservpoller starts a new one
# Config section - set the absolute path to where ginserv.py lives
scriptdir=/usr/local/src/ginlong2pvoutput
# End of config

cd "$scriptdir"

# If ginserv.py running, kill it
if pgrep -f ginserv.py >/dev/null; then
  pkill -f ginserv.py
fi
