#!/bin/bash

# Kill the current poller at night, so that it starts afresh for tomorrow
# Called just before midnight (so that today's files are today's

# Config section - set the absolute path to where ginserv.py lives
scriptdir=/usr/local/src/ginlong2pvoutput
# End of config

./killginservpoller

# Leave time for the run poller to rename the latest file
sleep 10

# Now gather today's files
# File names are ginserv.log_YYYYMMDD_HHMMSS, e.g. ginserv.log_20200710_215336
today=$(date '+%Y%m%d')
cat ginserv.log_$today* > logs/$today.ginserv.log

# Call the script that processes $today.ginserv.log and upload to pvoutput.org
./ginserv2pvoutput
